describe('Проверка покупки нового аватара', function () {                 
    it('e2e тест на покупку нового аватара для тренера', function () {   
         cy.visit('https://pokemonbattle.ru/');
         cy.get('.style_1_popup_white_title').should('be.visible');
         cy.get('.style_1_popup_white_title').contains('Битва покемонов');
         cy.get('.auth_content_text').should('be.visible');
         cy.get('.auth_content_text').contains('Войти с помощью');
         cy.get('.auth_content_social').should('be.visible');
         cy.get('#k_email').should('be.visible');
         cy.get('#k_password').should('be.visible');
         cy.get('.style_1_popup_white_link_left').should('be.visible');
         cy.get('.style_1_popup_white_link_left').contains('Восстановить');
         cy.get('.MuiButton-root').should('be.visible');
         cy.get('.MuiButton-root').contains('Войти');
         cy.get('.style_fix_1').should('be.visible');
         cy.get('.style_fix_1').contains('Зарегистрироваться');                       
         cy.get('input[id="k_email"]').type('USER_LOGIN');                   
         cy.get('input[id="k_password"]').type('USER_PASSWORD');               
         cy.get('button[type="submit"]').click();              
         cy.wait(2000);
         cy.get('.header_card_trainer').click();            
         cy.wait(2000);
         cy.get('.k_mobile > :nth-child(5) > #dropdown > img').click(); 
         cy.get('.available > button').first().click();   
         cy.get('.card_number').type('4620869113632996');                    
         cy.get('.card_csv').type('125');                             
         cy.get('.card_date').type('1226');                          
         cy.get('.card_name').type('IVAN IVANOV');
         cy.wait(2000);                           
         cy.get('.style_1_base_button_payment_body > .style_1_base_button_payment').should('be.visible');
         cy.get('.style_1_base_button_payment_body > .style_1_base_button_payment').contains('Оплатить');
         cy.get('.style_1_base_button_payment_body > .style_1_base_button_payment').click();     
         cy.wait(2000);
         cy.get('.style_1_base_input').type('56456');       
         cy.get('.style_1_base_button_payment_body > .style_1_base_button_payment').should('be.visible');
         cy.get('.style_1_base_button_payment_body > .style_1_base_button_payment').contains('Оплатить');
         cy.get('.style_1_base_button_payment_body > .style_1_base_button_payment').click();   
         cy.get('.payment_status_top_title').should('be.visible');
         cy.get('.payment_status_top_title').contains('Покупка прошла успешно');     
         cy.get('.style_1_base_link_blue').should('be.visible');
         cy.get('.style_1_base_link_blue').contains('Вернуться в магазин');
         cy.get('.style_1_base_link_blue').click();
     });
 });